apps/emotion_detection/urls.py
# Django imports
from django.urls import re_path

# app imports
from apps.emotion_detection import views

app_name = "emotion_detection"


urlpatterns = [
    re_path(r"^$", views.MainView.as_view(), name="main"),
    re_path(r"^detecator/$", views.DetectorView.as_view(), name="detecator"),
]

uni_project/urls.py
# Django imports
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, re_path

urlpatterns = [
    re_path(
        r"^login/$",
        auth_views.LoginView.as_view(template_name="core/login.html"),
        name="core_login",
    ),
    re_path(r"^logout/$", auth_views.LogoutView.as_view(), name="core_logout"),
    # enable the admin interface
    re_path(r"^admin/", admin.site.urls),
    re_path(r"", include("apps.emotion_detection.urls")),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/emotion_detection/models.py
# Django imports
from django.db import models


class TestModel(models.Model):
    name = models.CharField(max_length=50)

apps/emotion_detection/forms.py
# Django imports
from django import forms


class ImageForm(forms.Form):
    """Image form for initializing the main frontend variables"""
    image = forms.ImageField()
    emotion = forms.BooleanField(required=False)
    age = forms.BooleanField(required=False)
    race = forms.BooleanField(required=False)

    # add attributes to the image tag <img>
    image.widget.attrs.update({"class": "form-control", "id": "formFile"})

apps/emotion_detection/views.py
# Python imports
from base64 import b64encode
from io import BytesIO
from os.path import join
from posixpath import abspath

# Django imports
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import FormView, TemplateView

# external imports
import PIL.Image as Image

# app imports
from .forms import ImageForm
from .singlemotiondetector import SingleMotionDetector


class MainView(TemplateView):
    """ Main view for displaying the main page"""
    template_name = "index.html"

    def get(self, request, *args, **kwargs):
        print(dir(self.request))
        return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["url_class"] = "main"
        return context


class DetectorView(FormView):
    """ Form view to retrieve the images from
    the form and save to the local directory,
    and runs the SingleEmotionDetector class
    and return output to the frontend.
    """
    form_class = ImageForm
    template_name = "game2.html"

    def form_valid(self, form) -> HttpResponse:
        cleaned_data = form.cleaned_data

        # frontend checkboxs boolean values
        age, emotion, race = (
            cleaned_data["age"],
            cleaned_data["emotion"],
            cleaned_data["race"],
        )
        image_name, img_file = cleaned_data["image"].name, cleaned_data["image"].file

        # read the binary format of the file and save it to 'media/recieved_imgs/' directory
        file_binary = BytesIO.read(img_file)

        # relative path for the image that got to be process
        image_path = "media/recieved_imgs/" + image_name
        image_media_path = "static/media/recieved_imgs/" + image_name

        image = Image.open(BytesIO(file_binary))

        # save to the main media file
        image.save(image_path)

        # save to the static media file
        image.save(image_media_path)

        # django context variables for fronted usage
        context = self.get_context_data()

        if emotion:
            driver = SingleMotionDetector(image_path, "emotion")
        elif age:
            driver = SingleMotionDetector(image_path, "age")
        elif race:
            driver = SingleMotionDetector(image_path, "race")
        else:
            context["image"] = image_path
            return render(self.request, self.template_name, context)

        driver_output = driver()

        context["image"] = "/".join(driver_output.split("/")[1:])

        return render(self.request, self.template_name, context)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["url_class"] = "detecator"
        return context

    def get_success_url(self) -> str:
        return reverse("emotion_detection:main")

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--        Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!--        OwlCarousel  -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css"
          integrity="sha512-tS3S5qG0BlhnQROyJXvNjeEM4UpMXHrQfTGmbQ1gKmelCxlSEBUaxhRBj/EFTzpbP4RVSrpEikbmdJobCvhE3g=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <link rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.theme.default.min.css"
          integrity="sha512-sMXtMNL1zRzolHYKEujM2AqCLUR9F2C4/05cdbxjjLSRvMQIciEPCQZo++nk7go3BtSuK9kfa/s+a4f4i5pLkw=="
          crossorigin="anonymous" referrerpolicy="no-referrer"/>
    <!--        Google fonts & Icons -->
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700&display=swap"
          rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/boxicons.min.css' %}">
    <!-- <link rel="stylesheet" href="/static/css/boxicons.min.css"> -->

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <title>{% block page_name %}{% endblock %}</title>
</head>

<body>
    <header class="fixed-top">
        <nav id="navbar" class="navbar navbar-expand-lg navbar-light bg-white">
            <div class="container">
                <a class="navbar-brand logo-text" href="{% url 'emotion_detection:main' %}">Turtles</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                        aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                {% if url_class == 'main' %}
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="#home">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#plan">Plan</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#team">Team</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#about">Draft</a>
                        </li>
                    </ul>
                </div>
                {% endif %}
            </div>
        </nav>
    </header>

    {% block HTML_BODY %}
    {% endblock %}

    <footer class="fdb-block footer-small">
        <div class="container">
            <div class="row align-items-center text-center">
                <div class="col-12 col-lg-4 text-lg-left">
                    AIU 2021
                </div>
    
                <div class="col-12 col-lg-4 mt-4 mt-lg-0">
                    <h3>Turtles</h3>
                </div>
    
                <div class="col-12 col-lg-4 text-lg-right mt-4 mt-lg-0">
                    <ul class="nav justify-content-lg-end justify-content-center">
                        <li class="nav-item">
                            <a class="nav-link" href="#"><i class="bx bxl-facebook"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#"><i class="bx bxl-instagram"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#"><i class="bx bxl-twitter"></i></a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" href="#"><i class="bx bxl-github"></i></a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </footer>
    
    
    
    <!--            Option 1: Bootstrap Bundle with Popper -->
    <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
    <!--            Jquery cdn js  -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
            integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <!--            OwlCarousel cdn js     -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js"
            integrity="sha512-bPs7Ae6pVvhOSiIcyUClR7/q2OAsRiovw4vAkX+zJbw3ShAeeqezq50RIIcIURq7Oa20rW2n2q+fyXBNcU9lrw=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

templates/core/login.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
  <h2>Login</h2>
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Login</button>
  </form>
{% endblock %}

templates/detecator.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Detector</title>
</head>

<body>

  </form>
  {% if image %}

  <p>{{ image }}</p>
  <img id="img" src='{% static  "" %}' alt="Embedded Image">
  {% else %}

  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">

  {% endif %}

</body>

{% if image %}

<script>
  var img;
  img = document.getElementById("img")
  img.src = '/static/{{ image|safe}}'
</script>

{% endif %}

</html>

templates/game.html
{% extends 'base.html'%}
{% load static %}

{% block page_name %} Detecator {% endblock %}

{% block HTML_BODY %}
<section id="game">
  <div class="container">
    <form method="POST" enctype="multipart/form-data">
      {% csrf_token %}
      <div class="row justify-content-md-center">
        <div class="col-md-auto">
          <div>
            <label for="formFile" class="form-label"></label>
            {{ form.image }}
            <!-- <input class="form-control" type="file" id="formFile"> -->
          </div>
          {{ form.emotion }}
          {{ form.age }}
          {{ form.race }}
        </div>
      </div>
      <div class="row m-auto">
        <div class="col align-self-center">
          <div class="upload-img">
            <button href="#" type="submit" class="btn btn-brand">Submit</button>
          </div>
        </div>
      </div>
    </form>
  </div>
</section>
{% endblock %}

templates/game2.html
{% load static %}
<!doctype html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport"
    content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <!--        Bootstrap CSS -->
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css'%}">
  <!--        Google fonts & Icons -->
  <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@300;400;500;600;700&display=swap"
    rel="stylesheet">
  <link rel="stylesheet" href="{% static 'css/boxicons.min.css' %}">

  <link rel="stylesheet" href="{% static 'css/game-style.css' %}">
  <title>Detecator</title>
</head>

<body>

  <header class="fixed-top">
    <nav id="navbar" class="navbar navbar-expand-lg navbar-light bg-white">
      <div class="container">
        <a class="navbar-brand logo-text" href="#">Turtles</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav"
          aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      </div>
    </nav>
  </header>

  <section id="game">
    <div class="container">
      {% if image %}
      <div class="row m-auto">
        <div class="col align-self-center">
          <div class="upload-img">
            {% if image %}
            {{ image }}
            <img id="img" src='{% static  "" %}' alt="Embedded Image">
            {% endif %}
          </div>
          <a href="{% url 'emotion_detection:detecator'%}" class="btn btn-brand">Try Again</a>
        </div>
      </div>
      {% else %}
      <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="row justify-content-md-center">
          <div class="col-md-auto">
            <div>
              <label for="formFile" class="form-label"></label>
              {{ form.image }}
            </div>

            <div>
              <!-- <p>Detect</p> -->
              {{ form.emotion.label }} {{ form.emotion }}
              {{ form.age.label }} {{ form.age }}
              {{ form.race.label }} {{ form.race }}
            </div>
          </div>
        </div>
        <div class="row m-auto">
          <div class="col align-self-center">
            <div class="upload-img">
              {% if image %}
              {{ image }}
              <img id="img" src='{% static  "" %}' alt="Embedded Image">
              {% endif %}
            </div>
            <!-- <a href="#" class="btn btn-brand">Submit</a> -->
            <button type="submit" class="btn btn-brand">Submit</button>
          </div>
        </div>
      </form>
      {% endif %}


    </div>
  </section>


  <!--            Option 1: Bootstrap Bundle with Popper -->
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  <!--            Jquery cdn js  -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
    integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  {% if image %}
  <script>
    var img;
    img = document.getElementById("img")
    img.src = '/static/{{ image|safe}}'

  </script>
  {% else %}
  <script>
    emotion_cb = document.getElementById("id_emotion")
    age_cb = document.getElementById("id_age")
    race_cb = document.getElementById("id_race")

    emotion_cb.addEventListener('change', e => {
        if (emotion_cb.checked) {
            age_cb.checked = false;
            race_cb.checked = false;
        } else {
        }
    });

    age_cb.addEventListener('change', e => {
        if (age_cb.checked) {
            emotion_cb.checked = false;
            race_cb.checked = false;
        } else {
            return
        }
    });

    race_cb.addEventListener('change', e => {
        if (race_cb.checked) {
            emotion_cb.checked = false;
            age_cb.checked = false;
        } else {
            return
        }
    });
  </script>
  {% endif %}
</body>

</html>

templates/index.html
{% extends 'base.html'%}
{% load static %}

{% block page_name %} Turtles {% endblock %}

{% block HTML_BODY %}
<!--                                    HOME                -->
<section id="home">
    <div class="container text-center">
        <div class="row justify-content-center">
            <div class="col-md-10">
                <h1 class="display-4"><span class="it">IT' </span><span class="tu">Tu</span><span class="rt">rt</span><span class="le">le</span><span class="s">s</span></h1>
                <p class="qq">| willing to impress |</p>
<!--                <a href="#" class="btn btn-brand">yours to command</a>-->
            </div>
        </div>
    </div>
</section>

<!--                                    PLAN                -->
<section id="plan">
    <div class="container">
        <h2 class="h-title">Plan</h2>
        <div class="owl-carousel plan-carousel owl-theme">
            <div class="item">
                <h3>1'st week</h3>
                <div class="row justify-content-evenly">
                    <div class="col-lg-4 col-md-6 plan-box">
                        <h4 class="title-sm">start <span class="basis">| basis |</span></h4>
                        <p>--distribution of roles <br>--website layout
                        <br>--first part of emotion detector |gestures</p>
                    </div>
                    <div class="col-lg-4 col-md-6 plan-box">
                        <h4 class="title-sm">at the end of the week</h4>
                        <p>--ready basis <br>--discussion</p>
                    </div>
                </div>
            </div>
            <div class="item">
                <h3>2'nd week</h3>
                <div class="row justify-content-evenly">
                    <div class="col-lg-4 col-md-6 plan-box">
                        <h4 class="title-sm">start <span class="basis">| game |</span></h4>
                        <p>--making a game | emotion detector, gestures <br>--stylization of 'website </p>
                    </div>
                    <div class="col-lg-4 col-md-6 plan-box">
                        <h4 class="title-sm">at the end of the week</h4>
                        <p>--ready game <br>--ready website <br>--discussion
                        </p>
                    </div>
                </div>
            </div>
            <div class="item">
                <h3>3'rd week</h3>
                <div class="row justify-content-evenly">
                    <div class="col-lg-4 col-md-6 plan-box">
                        <h4 class="title-sm">start <span class="basis">| test |</span></h4>
                        <p>--beta-testing of the game <br>--beta-testing of the website <br>-- compilation of the presentation of the project</p>
                    </div>
                    <div class="col-lg-4 col-md-6 plan-box">
                        <h4 class="title-sm">at the end of the week</h4>
                        <p> <br><span class="mood"> Great mood!</span>
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<!--                                    TEAM                -->
<section id="team">
    <div class="container">
        <h2 class="h-title">Team</h2>
        <div class="owl-carousel team-carousel owl-theme">
            <div class="item">
                <div class="team-member">
                    <div class="team-member-img">
                        <img src="{% static '/img/yupr.jpg' %}" alt="">
                        <div class="social-icons">
                            <a target="_blank" href="https://www.instagram.com/yukishikai/"><i class="bx bxl-instagram"></i></a>
                        </div>
                    </div>
                    <div class="team-member-card">
                        <h5 class="member-card-title">Yuki</h5>
                        <span class="member-card-subtitle title-sm">frontend developer</span>
                        <div class="member-card-subtitle-line"></div>
                        <p class="member-card-description">
                          <span class="yuki">student | romantic</span> <br>sdfghjk
                        </p>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="team-member">
                    <div class="team-member-img">
                        <img src="{% static 'img/team-member.jpg' %}" alt="">
                        <div class="social-icons">
                            <a target="_blank" href="https://www.instagram.com/ibrmvva/"><i class="bx bxl-instagram"></i></a>
                        </div>
                    </div>
                    <div class="team-member-card">
                        <h5 class="member-card-title">.Gulya</h5>
                        <span class="member-card-subtitle title-sm">backend developer</span>
                        <div class="member-card-subtitle-line"></div>
                        <p class="member-card-description">
                            <span class="yuki">| agent 119 |</span> 
                        </p>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="team-member">
                    <div class="team-member-img">
                        <img src="{% static 'img/team-member.jpg' %}" alt="">
                        <div class="social-icons">
                            <a href="#"><i class="bx bxl-facebook"></i></a>
                            <a href="#"><i class="bx bxl-instagram"></i></a>
                            <a href="#"><i class="bx bxl-twitter"></i></a>
                            <a href="#"><i class="bx bxl-github"></i></a>
                        </div>
                    </div>
                    <div class="team-member-card">
                        <h5 class="member-card-title">Abdu.</h5>
                        <span class="member-card-subtitle title-sm">backend developer</span>
                        <div class="member-card-subtitle-line"></div>
                        <p class="member-card-description">
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis dolorum omnis
                            reiciendis sint
                            voluptate.
                        </p>
                    </div>
                </div>
            </div>
            <div class="item">
                <div class="team-member">
                    <div class="team-member-img">
                        <img src="{% static 'img/team-member.jpg' %}" alt="">
                        <div class="social-icons">
                            <a href="#"><i class="bx bxl-facebook"></i></a>
                            <a href="#"><i class="bx bxl-instagram"></i></a>
                            <a href="#"><i class="bx bxl-twitter"></i></a>
                            <a href="#"><i class="bx bxl-github"></i></a>
                        </div>
                    </div>
                    <div class="team-member-card">
                        <h5 class="member-card-title">Emir</h5>
                        <span class="member-card-subtitle title-sm">frontend developer</span>
                        <div class="member-card-subtitle-line"></div>
                        <p class="member-card-description">
                            Lorem ipsum dolor sit amet, consectetur adipisicing elit. Blanditiis dolorum omnis
                            reiciendis sint
                            voluptate.
                        </p>
                    </div>
                </div>
            </div>
        </div>
    </div>

</section>

<!--                                    ABOUT                -->
<section id="about">
    <div class="container">
        <h2 class="h-title">draft</h2>
        <div class="row text-center justify-content-between">
            <div class="col-lg-6">
                <h4 class="title-sm">About project</h4>
                <p>The models we will be developing can identify some human emotions as well as a few gestures. We will be trying to identify 6 emotions namely angry, happy, neutral, fear, sad and surprise. We will also be identifying 4 types of gestures which are loser, victory, super, and punch. We will be performing a real-time performance and we will be getting a real-time vocal response from the model. <br></p>
            </div>
            <div class="col-lg-6">
                <div class="about-problems">
                    <h4 class="title-sm">Problems</h4>
                    <p><span class="procras">| procrastination |
                    </span></p>
                </div>
                <div class="row">
                    <div class="col-sm-6 about-links">
                        <h4 class="title-sm">Links</h4>
                        
                            <!-- ? links -->
                            <a href="https://getbootstrap.com/" target="_blank">Bootstrap</a>
                            <!-- ? links -->
                    </div>
                    <div class="col-sm-6">
                        <h4 class="title-sm">ready?</h4>
                        <p class="em">| reveal your emotions |</p>
                        <a href="{% url 'emotion_detection:detecator' %}" target="_blank" class="btn btn-brand">Play</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}
